### PR TITLE
Null safety support

### PR DESCRIPTION
**Pull request by vmeretin**

### CODE REVIEW

**Comment by rafdls** [comment]
Hi @vmeretin ,

Thanks for the update re: null safety.
Hopefully, I'd be able to merge this one during the weekend.

I apologise for the delay.

Raf

**Comment by vmeretin** [comment]
Bump!

**Review by rafdls — APPROVED** [review]

**Comment by rafdls** [comment]
> Bump!

Hi @vmeretin! Merged it.

Anyway, any reason for renaming the packages?

I'm getting warnings publishing it because of different package name from the library name:

```
Package validation found the following potential issues:
* The name of "lib/headset_event.dart", "headset_event", should match the name of the package, "headset_connection_event".
  This helps users know what library to import.
```

**Comment by vmeretin** [comment]
I updated project files with shell command `flutter create . ...`.

I left `lib/headset_event.dart` as it is because don't want to make breaking changes.

If you want, you can rename dart file and class with matching of package name in additional commit to remove the warning.

**Pull request merged**
